version: '3'

volumes:
  postgres_data:
    driver: local

services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    networks:
      contractor:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${NGINX_EXPOSE_PORT}:80"
    depends_on:
      - php

  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    networks:
      contractor:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../../projects/contractor:/var/www:rw
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        - UID=$UID
    restart: unless-stopped

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    build:
      context: ./
      dockerfile: postgres/Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_NAME=${COMPOSE_PROJECT_NAME}
      - DATABASE_TESTING_NAME=${COMPOSE_PROJECT_NAME}_testing
    ports:
      - "${POSTGRES_EXPOSE_PORT}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./postgres/init.d/:/docker-entrypoint-initdb.d/"
    networks:
      contractor:
  
networks:
  contractor:
    external:
      name: contractor
